# Generated by Django 4.2 on 2023-04-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19C',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
    ]
